### PR TITLE
Fix #634, explictly set panel size to zero so it won't show up

### LINKED ISSUE #634: TeachingTip shows an addional white rectangle popup on Linux
**Describe the bug**

1. Add `<PropertyGroup><AvaloniaVersion>11.2.0</AvaloniaVersion></PropertyGroup>` to [`FAControlsGallery.Desktop.csproj`](https://github.com/amwx/FluentAvalonia/blob/3ef356a0919afd9859d0a5d420148d611a45f181/samples/FAControlsGallery.Desktop/FAControlsGallery.Desktop.csproj)
2. `dotnet run --project samples/FAControlsGallery.Desktop/FAControlsGallery.Desktop.csproj`
3. Open the page for `TeachingTip` and click button.

**Screenshots**
image

**Desktop/Platform (please complete the following information):**
 - OS: Ubuntu 24.04 (GNOME, Wayland)
 - FluentAvalonia Version: latest (or 2.2.0), commit 3ef356a0919afd9859d0a5d420148d611a45f181
 - Avalonia Version: 11.2.0 and up

**Additional context**

image

`300, 200` seems to be coming from [`Avalonia.X11/X11Window.cs`](https://github.com/AvaloniaUI/Avalonia/blob/07f3ad23e49da9ced46b7a68392e78a150622c35/src/Avalonia.X11/X11Window.cs#L165-L166). This bug seems to be caused by [commit `1cfa82ca`](https://github.com/AvaloniaUI/Avalonia/commit/1cfa82ca576260bd97864a9cf884fe48e3f7cabb) in Avalonia first released in `11.2.0-beta1`.

-----

<details>
<summary>Old incorrect bug description for archival purpose</summary>

**Describe the bug**

1. Change [`TargetFramework` of `FAControlsGallery.Desktop.csproj`](https://github.com/amwx/FluentAvalonia/blob/3ef356a0919afd9859d0a5d420148d611a45f181/samples/FAControlsGallery.Desktop/FAControlsGallery.Desktop.csproj#L4) from `net8.0` to `net9.0`
2. `dotnet run --project samples/FAControlsGallery.Desktop/FAControlsGallery.Desktop.csproj`
3. Open the page for `TeachingTip` and click button.

**Screenshots**
image

**Desktop/Platform (please complete the following information):**
 - OS: Ubuntu 24.04 (GNOME, Wayland)
 - FluentAvalonia Version: latest (or 2.2.0), commit 3ef356a0919afd9859d0a5d420148d611a45f181
 - Avalonia Version: tested on 11.1.0 and 11.2.2

**Additional context**
Only reproduced on dotnet 9. It works as intended on dotnet 8.

image

- On **dotnet 8**: [`_lightDismissIndicatorPopup.Child.Bounds`](https://github.com/amwx/FluentAvalonia/blob/3ef356a0919afd9859d0a5d420148d611a45f181/src/FluentAvalonia/UI/Controls/TeachingTip/TeachingTip.cs#L239) = `{0, 0, 0, 0}`
- On **dotnet 9**: `_lightDismissIndicatorPopup.Child.Bounds` = `{0, 0, 300, 200}`
- On both: `Width` and `Height` are always `NaN`, `DesiredSize` is always `{0, 0}`

`300, 200` seems to be coming from [`Avalonia.X11/X11Window.cs`](https://github.com/AvaloniaUI/Avalonia/blob/07f3ad23e49da9ced46b7a68392e78a150622c35/src/Avalonia.X11/X11Window.cs#L165-L166) but I'm not sure. Also I still have no idea why it behaves differently on dotnet 8 and 9.

</details>

### PR DESCRIPTION
**Pull request by Genteure**
See #634

image

### CODE REVIEW

File: src/FluentAvalonia/UI/Controls/TeachingTip/TeachingTip.cs [hunk 1]
```diff
@@ -236,7 +236,11 @@ private void CreateLightDismissIndiatorPopup()
         var popup = new Popup
         {
             // A Popup needs contents to open, so set a child that doesn't do anything.
-            Child = new Panel(),
+            Child = new Panel
+            {
```
Comment (amwx) [inline src/FluentAvalonia/UI/Controls/TeachingTip/TeachingTip.cs:240]: Can you add this comment here just so we (I) know why this is needed:
```C#
// See GH#634, Linux & mac have issue with empty popups, also Avalonia GH#17843
```

**Review by amwx — APPROVED** [review]

File: src/FluentAvalonia/UI/Controls/TeachingTip/TeachingTip.cs (hunk 1 above)
Comment (Genteure) [reply src/FluentAvalonia/UI/Controls/TeachingTip/TeachingTip.cs:241]: Comment added.
